name: Build and Test on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install make
        sudo apt install wget
        sudo apt-get install liburing-dev
    - name: Install Boost
      run: |    
        wget https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.gz
        tar xvf boost*.tar.gz
        sudo apt install build-essential g++ python3-dev autotools-dev libicu-dev libbz2-dev 
        cd boost_1_84_0/
        sudo ./bootstrap.sh --prefix=/usr/
        ./b2

    - name: Build project
      run: |
        cd lib_fits
        cmake -Bbuild
        make
        sudo cmake --build . --config Release --target install
        
    - name: Run tests
      run: |
        cd tests
        cmake -Bbuild
        cd build
        make
        ./tests
