name: Build and Test on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install make
        sudo apt-get install liburing-dev
        sudo apt-get install -y libcfitsio-dev
    
    - name: Update submodules
      run: git submodule update --init --recursive  
      
    - name: Build Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.84.0
        libraries: filesystem program_options system
        platform: x64
        configuration: Release

    - name: Build project
      run: |
        cd lib_fits
        cmake -Bbuild -D "BOOST_ROOT=${{ steps.boost.outputs.root }}" \
                      -D "BOOST_LIBRARYDIR=${{ steps.boost.outputs.librarydir }}"
        cd build
        make
        sudo cmake --build . --config Release --target install
        
    - name: Run tests
      run: |
        cd lib_fits/tests
        cmake -Bbuild -D "BOOST_ROOT=${{ steps.boost.outputs.root }}" \
                      -D "BOOST_LIBRARYDIR=${{ steps.boost.outputs.librarydir }}"
        cd build
        make
        ./tests 

    - name: Run experiment
      run: |
        cd experiment
        cmake -Bbuild -D "BOOST_ROOT=${{ steps.boost.outputs.root }}" \
                      -D "BOOST_LIBRARYDIR=${{ steps.boost.outputs.librarydir }}"
        cd build
        make
        ./experiment
