name: Build and Test on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build project
      run: |
        cd lib_fits
        cmake -Bbuild
        make
        sudo cmake --build . --config Release --target install
        
    - name: Run tests
      run: |
        cd tests
        cmake -Bbuild
        cd build
        make
        ./tests
